name: CI

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types:
      - published

jobs:
  build-distributions:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.8.3

      - name: Build distributions
        run: pixi exec python-build

      - name: Check package metadata
        run: pixi exec twine check dist/*

      - name: Publish package on PyPI
        if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
        uses: pypa/gh-action-pypi-publish@release/v1
