name: Distribution

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:

jobs:
  build-distributions:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.8.3

      - name: Build distributions
        run: pixi exec python-build

      - name: Check package metadata
        run: pixi exec twine check dist/*

      - name: Publish package on PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
